### ISSUE TITLE
New Discussions Microfrontend Experience (v1.6)

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#106]
### Product scope and features included

A new Discussion MFE with new user navigation pathways, enhanced options for viewing and browsing posts, functionality to like and follow posts, improve forum moderation, content search and organization and to create an interactive and better looking interface.

Specific enhancements include:

- Forum content organization into tabs
- Lists of learners documenting interaction with forums
- Moderator tools to endorse responses, specify post close reasons, specify reasons for edits
- Filers and sorts better organized
- Unified search experience
- Interactive post summaries
- Highlight reported, answered, endorsed and edited content

**Documentation details:**

- Link to Product blog and video demo: https://openedx.atlassian.net/wiki/spaces/OEPM/blog/2022/10/21/3560407218/2U+Discussion+Forum+Upgrades

- Link to "How to enable":

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-5c6e4858-7fff-4adc-e70e-cdfddf48d623"><div dir="ltr" style="margin-left:0pt;" align="left">

Feature | CourseWaffleFlag | Description | Prod | Default
-- | -- | -- | -- | --
Pages & Resources page in course-authoring-MFE | discussions.pages_and_resources_mfe | Once enabled, it shows navigation for Pages & Resources in the Studio navigation bar. Note: Configuration cards for Discussions MFE, teams and course Live appear on Pages & Resources page. | True | False
Teams configuration card on Pages & Resources page | teams.enable_teams_app | Shows teams course app card on the Pages & Resources page in course authoring MFE | True | False
ORA | openresponseassessment.team_submissions | Enable ORA Team submissions | True | False
Discussions MFE | discussions.enable_discussions_mfe | Enables the MFE for everyone in the Discussions tab. | True | False
discussions.enable_learners_tab_in_discussions_mfe | Enables learners tab for everyone in the Discussions tab. | True | False
discussions.enable_moderation_reason_codes | Enables addition and view of post edit and close reasons. | True | False
discussions.enable_learners_stats | Enables calculation and view of learner stats in forums. | True | False
discussions.override_discussion_legacy_settings | Not needed anymore | False | False
Email notifications for reported content | discussions.enable_reported_content_email_notifications | Users having discussion moderation privileges will receive email notifications when content is reported. Testing complete. Pending rollout. | False | False
BigBlueButton | course_live.enable_big_blue_button | Allows configuration of BigBlueButton in course Live app. Testing complete. Pending rollout. | False | False

</div></b>

- Link to any other relevant technical documentation:

### Community Release Information

**Product-ready details:**

- What's the production status as of the date of the code cut-off? 10/6: After rolling this out to edX customers, about 100 bugs and fixes were collated and are currently being addressed. Timeline for completion of bug fixes is end of Oct/early Nov. Biggest fixes include:
Topic sort is incorrect.
My posts only shows posts that a learner has created, and not all threads that they have interacted with.
Posts list for a particular learner in Learners tab cannot be sorted/filtered.
Learners tab and user search is not available to learners.
Learners tab is only showing 10 learners (pagination issue).
Learner stats UI needs to be descriptive.

- Primary contact: Aamir Ayub

**Child tasks include:**

- [x] https://github.com/openedx/platform-roadmap/issues/153
- [x] https://github.com/openedx/platform-roadmap/issues/158
- [ ] https://github.com/openedx/platform-roadmap/issues/154
- [x] https://github.com/openedx/platform-roadmap/issues/157
- [x] https://github.com/openedx/platform-roadmap/issues/155
- [x] https://github.com/openedx/platform-roadmap/issues/156

**Related milestones that will be rolled out simultaneously include:**

- [x] https://github.com/openedx/platform-roadmap/issues/74
- [x] https://github.com/openedx/platform-roadmap/issues/75
- [x] https://github.com/openedx/platform-roadmap/issues/76
- [x] https://github.com/openedx/platform-roadmap/issues/77

-----
Original documentation:

### Abstract and Goal

Goal: The new edX discussions MFE achieves feature parity with the legacy edX discussions experience. On completion of this Milestone, it will be available for selective preview.

Metric of success: Users will be able to create and edit posts, responses and comments in the correct post. 

This Milestone is part of Blended Development-38, a complete overhaul of the discussion experience for learners and moderators to support rich course, program and platform-level communities and collaboration. 

### Approach and Scope

The new MFE experience will not be a new discussion app type, but will be an alternate experience for the legacy edX discussions app.  This means, rather than enabling it by configuring a new discussions app, we can preview it for existing integrations via a course waffle flag.

### Related Documentation

Jira Milestone: https://openedx.atlassian.net/browse/TNL-7793

Design spec: See "Discussion preview" section: https://www.figma.com/file/LVFnO9oRHYiamoicZuXDAC/Discussion-page

**Comment by jmakowski1123** [comment]
Update on bug fixes since Oct 10:

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-20599d46-7fff-2dbe-e368-3eae200027be"><div dir="ltr" style="margin-left:0pt;" align="left">

Milestone | Code commit | Severity
-- | -- | --
Discussions MFE | Reported label was not working properly in the Learners tab. | Minor inconvenience
Option to sort users by Recent activity in Learners tab. | New feature
Segment events for content report, edit and close activity. | New feature
Reported action fixed for some course roles. | Minor inconvenience
Topics in units belonging to not-yet-released sections were visible. | Minor inconvenience
Usernames should be clickable in post summary. | Minor inconvenience
Filter options for posts of any learner in the Learners tab. | Minor inconvenience
Banner for when blackout dates are active | New feature
Enable learners tab for learners. | Major inconvenience
Edit reason fix for global staff role. | Major inconvenience
Text editor and preview auto resize. | Minor inconvenience
Fixed topic sort in topic tab. | Major inconvenience
Added support for more mathjax syntaxes | Minor inconvenience
Documentation updates | Minor inconvenience
BigBlueButton | Disable free tier by default | Required to function
Reported email notifications | Enable notifications through Braze. | Not sure

</div></b>

**Comment by jmakowski1123** [comment]
@arbrandes Want to flag updates on this ticket to you. Aamir kindly provided feature toggle info for the MFE, which I've copied as a table in the main body of this ticket. 

Additionally, in the comment above, there are updates on the WIP bug fixes. I'm trying to clarify if these bugs are all fixed and good to go, and whether there are any additional bugs in progress.

**Comment by arbrandes** [comment]
@jmakowski1123, I'm not clear on the bug fixes:

* Are all those listed fixed?
* Is BigBlueButton optional?  It looks like it, as there's a flag to enable it, but the "Required to function" severity might suggest otherwise.
* Are there any other major inconveniences left to fix at this point?  Is there a canonical list where this is being tracked?  Doesn't matter if it's a Google doc or wiki page, as long as its public.

To be clear, if this is to make it into Olive, we need to find out about the above in the next couple of days: if the MFE passes the this bar, we still need to add dynamic configuration support and add it to tutor-mfe, both of which take some time.  After _that_, translators and testers in the TWG/BTR need time for their own work.

**Comment by jmakowski1123** [comment]
> @jmakowski1123, I'm not clear on the bug fixes:
> 
> * Are all those listed fixed?
-List is updated now with the current statues

> * Have they been backported to the corresponding `open-release/olive.master` branches of affected repos?  (the MFE itself doesn't have that branch, which is actually a good thing at this point - but the fixes might affect cs_comments_service and/or edx-platform, which _do_ have the branch)
-Don't know - I'm following up with Aamir


> * Is BigBlueButton optional?  It looks like it, as there's a flag to enable it, but the "Required to function" severity might suggest otherwise.
-Yes, it's optional. The "required to function" fix was tied to removing the free tier option in configuring the app (a private arrangement between the app provider and edx). It needed to be removed prior to making it available in the release, and that work is done.

> * Are there any other major inconveniences left to fix at this point?  Is there a canonical list where this is being tracked?  Doesn't matter if it's a Google doc or wiki page, as long as it's public.
-According to Aamir: No more major inconveniences or required to function fixes. There are no more blocking issues in progress or the backlog.

**Comment by arbrandes** [comment]
Awesome, thanks @jmakowski1123!  This is looking much more promising, now. :)

**Comment by arbrandes** [comment]
Done!

**Comment by arbrandes** [comment]
Are we done here, @jmakowski1123?

**Comment by arbrandes** [comment]
I think we're done. :)
