### ISSUE TITLE
MySQL 8 Support

### ISSUE THREAD

**Issue by e0d** [openedx/platform-roadmap#119]
This is the epic for tracking all work required to support MySQL 8 for the Open edX platform.

Currently, MySQL 5.7 is supported.  It has an EOL date of Oct 2023.

We are already aware of some issues the require attention that will be linked to this epic.

The Data Working Group has proposed the following overall timeline for MySQL 8 support.

1. Nutmeg: MySQL 5.7 on the server side, and ARM64 dev environments can use MariaDB 10.4
2. Olive: Support both MySQL 5.7 and 8.0 on the server side, and ARM64 dev environments will move to MySQL 8.0
3. Palm release: Support MySQL 8.0 only

- [ ] https://github.com/openedx/platform-roadmap/issues/120
- [x] https://github.com/openedx/platform-roadmap/issues/121
- [ ] (post migration): Change configuration to default to `utf8mb4` encoding and `utf8mb4_0900_ai_ci` collation.
- [ ] (post migration): Do discovery work to determine a strategy for upgrading all tables to this (keeping in mind that some columns will want to use binary collation).  (@ormsbee's note: We're free of the 767 byte InnoDB limit on newer row storage formats, but I'm not sure what the performance impact is.)

**Comment by tecoholic** [comment]
We at OpenCraft did a discovery for the MySQL 8 compatibility. At the end of the discovery it was 
identified that the Django DB migrations of a number of edx-enterprise 
applications are failing due to a bug in MySQL 8.

**Core Issue**

MySQL [changed the way](https://dev.mysql.com/doc/refman/8.0/en/identifier-length.html) CHECK constraints are named in version 8. From version 8, it adds an extra `_chck_` followed by a number to the CHECK constraint names. This is done 
implicitly by MySQL when a new column is created with CHECK constraint.

For example:

```sql
CREATE TABLE `blackboard_blackboardlearnerassessmentdatatransmissionaudit` (
--
`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
`enterprise_course_enrollment_id` integer UNSIGNED NOT NULL CHECK (`enterprise_course_enrollment_id` >= 0)
)
```

When the table names are extra long, as in the above example, the implicitly created name for the check constraint exceeds the Identifier limit of 64 causing the DB to fail the migration with (1059, Identifier Name Too Long) error.

### Probable solutions identifier

There are 3 places this could be fixed:

#### 1. MySQL 8

Since this is not a user provided identifier and instead auto generated by the DB, ideally, the DB should ensure the length of the 
identifier is within the limit of 64 chars. So, this should be fixed at the MySQL level.

However, this would be a long and tedious process and the rollout of the fix might take long.

#### 2. Django Migration

MySQL 8 also supports an additional syntax for creating CHECK constraint. The regular syntax is

```sql
CHECK (expr)
```

Version 8.0.16 added support for creating CHECK constraint with an explicit name:

```sql
[CONSTRAINT [symbol]] CHECK (expr) [[NOT] ENFORCED]
```

Django <a href="https://github.com/django/django/blob/0b95a96ee10d3e12aef01d449467bcf4641286b4/django/db/backends/base/schema.py#L78" class="external-link" rel="nofollow" title="Follow link">currently generates the SQL for migrations using the older syntax</a>. If Django can be patched to use the newer syntax and perform the duty of ensuring the constraint name is limited to 64 chars when using MySQL. This would solve fix the migration issue, not just for the 
edx-enterprise apps, but for any Django app that might run into this 
issue.

#### 3. Renaming edx app Table/Column/Constraint

If Django would not handle such a fix, then the relevant entity of the edx application needs to be renamed in such a way that the CHECK constraint name doesn't go over 64 characters.

During the course of the discovery, the following migrations were identified as having issues:

- `blackboard.0005_blackboardlearnerassessmentdatatransmissionaudit`
- `sap_success_factors.0001_squashed_0022_auto_20200206_1046`

I hope this is helpful for people working on this issue.

**Comment by ormsbee** [comment]
Update: Per @jmbowman, we're going to aim to be able to run Nutmeg on MySQL 8.0.

**Comment by jfavellar90** [comment]
Hi @ormsbee @jmbowman. In the BTR we are looking at the critical issues for the Nutmeg cut in April. Could you please confirm if MySQL 8.0 is still a goal for Nutmeg? Thank you in advance

**Comment by ormsbee** [comment]
@jfavellar90: Talked with @jmbowman today and confirmed that they're still targeting MySQL 8.0 for Nutmeg (and that things are looking good so far). Nutmeg should be compatible with both 5.7 and 8.0, and edX itself won't migrate their site off of 5.7 until after Nutmeg has been cut.

**Comment by ormsbee** [comment]
Nutmeg introduced [a bug with course section titles](https://discuss.openedx.org/t/nutmeg-upgrade-outlines-py-openedx-core-djangoapps-content-learning-sequences-models-learningcontext-doesnotexist-learningcontext-matching-query-does-not-exist/7892/8?u=dave) because our tables are still using the old utf8 encoding and not utf8mb4.

**Comment by sarina** [comment]
Closing as this is marked "Shipped" on the PR board 🎉
