### ISSUE TITLE
Tutor Adoption 5: Plugin Ecosystem

### ISSUE THREAD

**Issue by kdmccormick** [openedx/platform-roadmap#123]
### Goal

In [Stable Plugin API epic](https://github.com/openedx/platform-roadmap/issues/116), we designed, implemented, documented, and released a V1 Plugin API for Tutor.

Now, we can follow and up and ensure:
* Folks are finding the new API easy to learn.
* Folks are finding the that the API contains all the features that they need.
* The API is fully documented (it is largely documented, but there are still gaps).
* Official plugins that still using V0 are upgraded to V1.
* There is a list of plugins, there maintainers, and their support statuses.
* Plugin maintainers are encouraged to keep their plugins up-to-date.

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/wg-developer-experience/issues/75
- [ ] https://github.com/openedx/wg-developer-experience/issues/130
- [ ] https://github.com/overhangio/cookiecutter-tutor-plugin/issues/15
- [ ] https://github.com/openedx/wg-developer-experience/issues/121
- [ ] https://github.com/openedx/wg-developer-experience/issues/55
- [ ] https://github.com/openedx/wg-developer-experience/issues/49
- [ ] https://github.com/openedx/wg-developer-experience/issues/50
- [ ] https://github.com/openedx/wg-developer-experience/issues/46
- [ ] https://github.com/openedx/wg-developer-experience/issues/44
- [ ] https://github.com/openedx/wg-developer-experience/issues/125
- [ ] https://github.com/openedx/wg-developer-experience/issues/131
- [ ] https://github.com/openedx/wg-developer-experience/issues/51
- [ ] https://github.com/overhangio/cookiecutter-tutor-plugin/issues/7
- [ ] https://github.com/openedx/wg-devops/issues/34
- [ ] https://github.com/openedx/wg-devops/issues/33
- [ ] https://github.com/openedx/wg-devops/issues/32
- [ ] https://github.com/openedx/wg-developer-experience/issues/68
- [ ] https://github.com/openedx/wg-devops/issues/31
- [ ] https://github.com/openedx/wg-developer-experience/issues/67
- [ ] https://github.com/openedx/wg-devops/issues/30
- [ ] https://github.com/openedx/wg-devops/issues/29
- [ ] https://github.com/openedx/wg-devops/issues/27
- [ ] https://github.com/openedx/wg-devops/issues/28
- [ ] https://github.com/openedx/wg-developer-experience/issues/135
```

**Comment by kdmccormick** [comment]
I'm closing this, as there is no longer a concerted effort to work on these things, although the Tutor Maintainers team or the [DevOps WG](https://github.com/openedx/wg-devops/issues) may continue to chip away.
