### ISSUE TITLE
Open edX Documentation Restructure: Discovery

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#130]
Final discovery artifact available here for comment: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3389849714/Discovery+Proposal+Open+edX+Documentation+Restructure

### Abstract

tCRIL is undertaking a discovery initiative to learn more about pain points and challenges in the Open edX Documentation ecosystem. Barriers to documentation use and maintenance have been noted for years, but there has never been a comprehensive investigation into the full scope of the problem. This discovery initiative is intended to fully understand the scope, as well as make recommendations for an approach to address them. 

### Context & Background

Over the years of its existence, the documentation to support Open edX has grown and evolved organically. Without a clear end-to-end information strategy to guide the creation and organization of the documentation, and without a clear definition of users’ end goals, a number of problems have arisen:

- Open edX documents things in many places. It’s messy, without a clear strategy for what types of docs should live where and why, and for whom docs are intended.

- It’s not clear to end-users where to look for the right documentation to address their questions or to learn the platform. It’s also not clear to contributors where to put new documentation, or how to improve current documentation.

- Information is often out of date.

- Docs.edx.org is specific to edx.org

Documentation is less developed, or not organized in the most appropriate way, for certain types of users, for example faculty/course authors. One Instance administrator noted that [some Open edX Documentation](https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/index.html) is actually a barrier of entry for faculty, rather than a facilitator to entry.

### Scope & Approach

We divided this discovery initiative into two parts.

First, we focused on understanding “the what, the why and the who” - namely, who are the documents for, what problems do they solve, and as a result, what types of documents do we need? We wanted to reframe the documentation goals around addressing pain points and needs for different types of users.  

- Conducted an audit of all current documentation
- Conducted user interviews to understand pain points and what doc needs are

Then, we used those findings to inform questions around “the where and the how” - Where should the documents live and how should they be organized?

- Conducted best practices research

### Value & Impact

Fixing the problems noted above will have positive impacts for everyone who uses Open edX:

- It will support an increase in platform adoption by making it easier for developers and IT staff to install and to upgrade.

- It will support an increase in usage for non-tech oriented audiences.

- It will make it easier for the open source community to contribute to document upkeep and maintenance, resulting in a more robust and self-sustaining ecosystem.

### Milestones and/or Epics

- [x] https://github.com/openedx/tcril-engineering/issues/104
- Goal is to compile a list of all current Open edX Documentation. It will be useful in later project stages as decisions are made about which documents to keep, which to update, which to eliminate.

- [x] https://github.com/openedx/tcril-engineering/issues/103
- Goal is to build One Day In The Life profile for each persona that clearly answers the following: 1) What key problems would one or more documents solve for this person? 2) What documents do they need/do they use?

- [x] https://github.com/openedx/tcril-engineering/issues/184
- Distill strengths from other open source documentation initiatives in the same sector.

- [ ] https://github.com/openedx/tcril-engineering/issues/60
- The targeted outcome is a Discovery Artifact in the form of a proposal with a visual "show and tell" with recommendations based on our discovery work that we can circulate to the community for feedback.

### Named Release

n/a

### Timeline

We aim to circulate the Discovery Artifact with recommendations to the community for feedback during the first week of April. We will open multiple spaces for conversation at the conference, including a Documentation presentation and birds of a feather. 

### Proposed By

tCRIL

### Additional Info

Recommendations and Proposal: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3389849714/Discovery+Proposal+Open+edX+Documentation+Restructure

**Comment by jmakowski1123** [comment]
Final discovery artifact available here for comment: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3389849714/Discovery+Proposal+Open+edX+Documentation+Restructure
