### ISSUE TITLE
Deprecate Duplicative Features

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#132]
### Abstract

This deprecation work is being undertaken as part of a General Deprecation project funded by tCRIL to expedite a backlog of deprecation debt. The goal of this project is to finish the removal of several unfinished deprecation tickets that we have not been able to complete ourselves due to time constraints.

**Project-level metrics:**

Impact: Ease of development/time to market.
Measure: DEPR tickets moved to 'Removed' and LOC removed.

### Context & Background

We have many deprecation projects in the pipeline and that have been announced to the community, but we don't have the resources to remove all the technology ourselves. We have allotted a general bucket of hours that we can devote to deprecation work to help reduce the pain and complexity of this 'dead' code for future engineers. There are a few general categories of deprecations that we have chosen to focus on:

- Unsupported libraries
- Multiple versions of the same feature
- Incomplete migrations
- MFE replacement work

### Scope & Approach

This issue covers the deprecation work that falls into the category of: Deprecating multiple versions of the same feature.

- [ ] https://github.com/openedx/public-engineering/issues/56

- Goal: Remove old course info page from ~2015's shift away from this page. This includes other code no longer in use relating to when we had the course info page (titled "Courseware") as the main course page. Included in this is the accordion that shows the course outline in the sidebar of the course content pages. 

- [ ] https://github.com/openedx/public-engineering/issues/61

- Goal: We are in the process of building a new service that will replace the existing enterprise catalog functionality, so we plan to deprecate and remove the existing endpoints at the point when we have the new ones up and running.

- [ ] https://github.com/openedx/public-engineering/issues/28

- [ ] https://github.com/openedx/public-engineering/issues/63

### Value & Impact

- Reduce cost time to maintain
- Reduce confusion for developers
- Reduce developer churn

### Milestones and/or Epics

1. See: https://github.com/openedx/public-engineering/issues/56
2. See: https://github.com/openedx/public-engineering/issues/61
3. See: https://github.com/openedx/public-engineering/issues/28
4. See: https://github.com/openedx/public-engineering/issues/63

### Named Release

unknown

### Timeline

1. See: https://github.com/openedx/public-engineering/issues/56
2. See: https://github.com/openedx/public-engineering/issues/61
3. See: https://github.com/openedx/public-engineering/issues/28
4. See: https://github.com/openedx/public-engineering/issues/63

### Proposed By

tCRIL

**Comment by jmakowski1123** [comment]
being tracked in the depr board
