### ISSUE TITLE
Deprecate Incomplete Migrations

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#133]
### Abstract

This deprecation work is being undertaken as part of a General Deprecation project funded by tCRIL to expedite a backlog of deprecation debt. The goal of this project is to finish the removal of several unfinished deprecation tickets that we have not been able to complete ourselves due to time constraints.

**Project-level metrics:**

Impact: Ease of development/time to market.
Measure: DEPR tickets moved to 'Removed' and LOC removed.

### Context & Background

We have many deprecation projects in the pipeline and that have been announced to the community, but we don't have the resources to remove all the technology ourselves. We have allotted a general bucket of hours that we can devote to deprecation work to help reduce the pain and complexity of this 'dead' code for future engineers. There are a few general categories of deprecations that we have chosen to focus on:

- Unsupported libraries
- Multiple versions of the same feature
- Incomplete migrations
- MFE replacement work

### Scope & Approach

This issue covers the deprecation work that falls into the category of: Incomplete Migrations

- [ ] https://github.com/openedx/public-engineering/issues/35

- Goal: The save param will be removed from anonymous_id_for_user (https://github.com/edx/edx-platform/blob/80a4437f338b6dbe16bfd57a1477fc3ede6a24df/common/djangoapps/student/models.py#L157) and unique_id_for_user.

- [ ] https://github.com/openedx/public-engineering/issues/27

- Goal: edX-platform currently has code for both PDF and web (or HTML) course certificates. Over time, much of the PDF certificate code has been deprecated or disabled in favor of web certificates. In particular, edX-platform has not supported the generation of PDF course certificates for some time. This DEPR ticket covers the removal of the code in edx-platform that allows PDF certificates to be viewed. PDF course certificates will no longer be viewable.

- [ ] https://github.com/openedx/public-engineering/issues/14

- Goal: edx-jsme is an XBlock for the edX platform which provides a new problem type: 'Molecular Structure'. This problem type integrates the JSME molecule editor seamlessly into an edX course. The Molecular Structure Problem type was only ever used by one course on edx.org and the original authors of the xBlock are not available to upgrade it. We will remove the edx-jsme xblock from the standard edX requirements.

### Value & Impact

- Completing these workstreams will reduce confusion for developers and streamline workflows.

### Milestones and/or Epics

1. See: https://github.com/openedx/public-engineering/issues/35
2. See: https://github.com/openedx/public-engineering/issues/27
3. See: https://github.com/openedx/public-engineering/issues/14

### Named Release

unknown

### Timeline

1. See: https://github.com/openedx/public-engineering/issues/35
2. See: https://github.com/openedx/public-engineering/issues/27
3. See: https://github.com/openedx/public-engineering/issues/14

### Proposed By

tCRIL

**Comment by jmakowski1123** [comment]
being tracked in the depr board
