### ISSUE TITLE
Concept doc for ALUs

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#142]
Scope adjustment 6/9 - This has morphed into an SOW outlining milestones to reach complete product documentation to guide the ALU project. Marking as done.

### Abstract

In order to guide and clarify discovery work currently in progress on: https://github.com/openedx/platform-roadmap/issues/67 

and build on discovery work completed on: https://github.com/openedx/platform-roadmap/issues/2

### Context & Background

This epic is intended to connect, inform and support discovery work that is currently underway to explore creating a modularized content/course authoring experience of the Open edX platform: 

@bradenmacdonald outlined a diverse range of authoring improvements and use cases that could be implemented with a re-architecting of the platform to support the creation of courses based on atomic learning units: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3378118892/Discovery+Courses+Based+on+Atomic+Learning+Units

@jmakowski1123 compiled a diverse range of use cases based on market and user feedback that would rely on a more flexible model for building and sequencing atomic learning units together: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3400663102/A+Modular+Open+edX+Experience

On the architecture side, @ormsbee is outlining discovery milestones to explore more flexible LMS content data models and an MVP unit composition prototype: https://github.com/openedx/platform-roadmap/issues/67

We met to explore the points of intersection between these Initiatives, particularly in the overlapping use cases that such a re-architecting could support. As next steps:

We decided to prioritize one subgroup of use cases to define in more detail. That subgroup of use cases are:

- As a learning provider, I want to offer mini-courses that are smaller, simpler, and lighter than the current course experience. I don't want to be limited to the strict Sections, Subsections, Units hierarchy.Paths.

- As a learning provider, I want to design a learning objective around a single video or webinar, with associated comprehension questions, and delivering as a complete learning experience. 

- As a learning provider, I want to create and deliver a single module as a complete learning experience, or a unit within a module as a complete learning experience.

- As a learning provider, I want to create customized sets of questions, assessments or question banks as complete learning experiences. 

There are a number of commonalities underlying the above use cases:

- They are contingent on creating alternative methods to building and sequencing learning content. The current model offered in Studio is based on a top-down, fairly prescription method, that cascades down from Course Objective --> modules --> units --> subunits --> learning objects. These use cases are contingent on enabling a bottom-up approach.
- They are not reliant on a full course as the end goal for delivery. 

As a next step, we need to further define the scope, parameters and expectations around these use cases, what we are currently calling "mini learning experiences". We need an MVP use case to help guide and inform architectural discovery work and to test assumptions that this new model of authoring would meet a clear set of user needs. 

### Scope & Approach

We should take an agile approach to defining this use case MVP. For the moment, we are calling it a "mini learning experience MVP", but even that needs to be tested.

One of the most effective ways to build a reliable and robust MVP use case is to involve target users to help define it. We need clarity on many questions, such as:

- What are the expectations for delivering a "mini learning experience"? Via an Instance? Via third party platforms?
- What are the expectations for sequencing atomic learning units? 
- What are the sources of the learning objects? Content libraries? xblocks? External repositories or libraries?
- Does it require enrollment? 
- What are the expectations around assessments and grading? 
- What are the expectations for real-time feedback/analytics?

I'd like to explore putting together an advisory board of users - faculty and/or learning providers - and a systematic feedback loop to help us clarify these questions. The end goal would be:

A clearly defined use case that answers the above questions and more
A clear scope and understanding of what the minimum viable "product/feature" would require
A sketch of the authoring experience

### Value & Impact

Value to educators, faculty, SMEs, course designers, course authors:

Improves authoring by enabling a pedagogy-first pathway through the course design experience. Educators are freed to focus on designing learning objectives first, and building and sequencing learning pathways to achieve them, from the ground up, rather than molding learning pathways into a prescriptive, top-down course→module—> unit structure.

Empowers educators/course teams to define the boundaries of learning experiences and align them to more particular and diverse learner needs and outcomes.

### Milestones and/or Epics

- [ ] Identify and assemble an advisory group of 5-7 target users
- [ ] Define a workflow and touch points with clear outcomes and deliverables
- [ ] Define metrics to gauge interest/scope of potential use

### Named Release

n/a

### Timeline

n/a

### Proposed By

tCRIL

**Comment by jmakowski1123** [comment]
Update with perspective from the conference:

I think we have an opportunity to scope the project with a community-wide view of the problem, goal, and user needs. OpenCraft has done discovery work, but others are thinking about it too (edly as one example, and obvs edX, and MIT....). There is also user input from instances like WGU, Penn, [Campus.IL](http://campus.il/). I'm trying to figure out the best method for compiling and analyzing that landscape view so that we can define a PRD as inclusively as possible. The intent is to head off duplicative work AND help us think strategically about how the initiative can add maximal value to as many stakeholders as possible (edX included)

I came up with this scratchpad as a starting point: https://lucid.app/lucidchart/4aa8ed6f-0fac-41db-9f84-42895311b348/edit?beaconFlowId=DD006CC216290D68&invitationId=inv_82bba75f-9e3d-4387-8c47-a0e9e457e898&page=0_0#

**Comment by bradenmacdonald** [comment]
@jmakowski1123 I don't have access to that document; would you mind checking the permissions?
