### ISSUE TITLE
Tutor Adoption 6: More Dev QOL

### ISSUE THREAD

**Issue by kdmccormick** [openedx/platform-roadmap#152]
### Goal

Second round of quality-of-life ("QOL") improvements to the Open edX development experience in Tutor. Continues https://github.com/openedx/platform-roadmap/issues/122, which was released in Nutmeg.

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/wg-developer-experience/issues/45
- [ ] https://github.com/openedx/wg-developer-experience/issues/26
- [ ] https://github.com/openedx/wg-developer-experience/issues/88
- [ ] https://github.com/openedx/wg-developer-experience/issues/89
- [ ] https://github.com/openedx/wg-developer-experience/issues/6
- [ ] https://github.com/openedx/wg-developer-experience/issues/15
- [ ] https://github.com/openedx/wg-devops/issues/26
- [ ] https://github.com/openedx/edx-platform/issues/32353
- [ ] https://github.com/openedx/wg-developer-experience/issues/51
- [ ] https://github.com/openedx/wg-developer-experience/issues/74
- [ ] https://github.com/openedx/wg-developer-experience/issues/63
- [ ] https://github.com/openedx/wg-devops/issues/36
- [ ] https://github.com/openedx/wg-devops/issues/37
- [ ] https://github.com/openedx/wg-developer-experience/issues/64
- [ ] https://github.com/openedx/wg-devops/issues/18
```

**Comment by kdmccormick** [comment]
I'm closing this, as there is no longer a concerted effort to work on these things, although the Tutor Maintainers team or the [DevOps WG](https://github.com/openedx/wg-devops/issues) may continue to chip away.
