### ISSUE TITLE
Tutor Adoption 4: Devstack Parity

### ISSUE THREAD

**Issue by kdmccormick** [openedx/platform-roadmap#202]
### Abstract

We want Tutor's dev mode to be as-good-as or better than Devstack for common edx-platform developer workflows, including:

* previewing changes to a service (edx-platform or otherwise), either master and latest release
* previewing changes to MFEs, either master and latest release
* updating & testing requirement upgrades in a service
* making changes to a specific Python package/plugin and seeing them manifest in a service 
* making changes to a specific JS package/plugin and seeing them manifest in an MFE
* adding new services (via plugins, for Tutor)

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/wg-developer-experience/issues/146
- [ ] https://github.com/openedx/wg-developer-experience/issues/131
- [ ] https://github.com/openedx/wg-developer-experience/issues/132
- [ ] https://github.com/openedx/wg-developer-experience/issues/133
- [ ] https://github.com/openedx/wg-devops/issues/24
- [ ] https://github.com/openedx/wg-devops/issues/23
- [ ] https://github.com/overhangio/tutor-forum/issues/23
- [ ] https://github.com/openedx/wg-devops/issues/25
- [ ] https://github.com/openedx/wg-developer-experience/issues/164
- [ ] https://github.com/openedx/wg-developer-experience/issues/144
- [ ] https://github.com/openedx/wg-developer-experience/issues/66
- [ ] https://github.com/openedx/wg-developer-experience/issues/81
- [ ] https://github.com/openedx/wg-developer-experience/issues/156
- [ ] https://github.com/openedx/wg-developer-experience/issues/71
- [ ] https://github.com/openedx/wg-developer-experience/issues/58
- [ ] https://github.com/openedx/wg-developer-experience/issues/56
- [ ] https://github.com/openedx/wg-developer-experience/issues/43
- [ ] https://github.com/openedx/wg-developer-experience/issues/41
- [ ] https://github.com/openedx/wg-developer-experience/issues/127
- [ ] https://github.com/openedx/wg-developer-experience/issues/86
- [ ] https://github.com/openedx/wg-developer-experience/issues/85
- [ ] https://github.com/openedx/wg-developer-experience/issues/53
- [ ] https://github.com/openedx/wg-build-test-release/issues/235
- [ ] https://github.com/openedx/wg-developer-experience/issues/36
- [ ] https://github.com/openedx/wg-developer-experience/issues/120
- [ ] https://github.com/openedx/wg-developer-experience/issues/145
```

**Comment by kdmccormick** [comment]
This is mostly done! A couple follow-ups, but I feel to close this out.
* https://github.com/openedx/wg-devops/issues/25
* https://github.com/openedx/wg-devops/issues/23
* https://github.com/openedx/wg-devops/issues/24
