### ISSUE TITLE
New feature: Copy/Paste from one course to another - components, units, subsection and sections

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#210]
To track this work in granular detail, see:

- The project board: https://github.com/orgs/openedx/projects/36/views/1
- The gantt chart: https://docs.google.com/spreadsheets/d/1XIbyiul_Br1UDrX1K6UqrcH3z_jhFyXnk6qpOdqidDU/edit#gid=0

### User story: 

As a course author, I want to copy any part of my course and reuse it in another course. This include components, units, subsections and sections.

### MVP Deliverable: 

A lightweight functionality that enables authors to reuse components, units, subsections and sections by sharing directly from one course to another. Reuse functionality will extend to static pages as well. For this first MVP, the content is copied as a one-time action, and any future edits made to either copy won’t be synced. However, it is possible to edit the component independently in its new environment.

### Impact:

Reduce authoring time by enabling authors to reuse course components.

### Design Frames: 

https://www.figma.com/file/y2qfzidTxxfYK8ONgyT7KP/Modular-Learning-Wireframes?node-id=0%3A1

### Milestones: 

- [ ] M0, Design frames: https://github.com/openedx/modular-learning/issues/6

- [ ] M1, Studio prototype for component copy/paste: https://github.com/openedx/modular-learning/issues/1

- [ ] M2, Release of component copy/paste: https://github.com/openedx/modular-learning/issues/2

- [ ] M2.5, Copy component from studio to library: https://github.com/openedx/modular-learning/issues/33

- [ ] M3, Release of unit copy/paste: https://github.com/openedx/modular-learning/issues/3

- [ ] M4, Release of subsection copy/paste: https://github.com/openedx/modular-learning/issues/4

- [ ] M5, Release of section copy/paste: https://github.com/openedx/modular-learning/issues/5
