### ISSUE TITLE
New MFE: Learner Dashboard

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#217]
### Product scope

- The new Learner Home has many of the same features of the old dashboard, with some extended functionality and performance enhancements.
- This release brings the learner home  into our current MFE architecture, and will enable much faster experimentation on the learner homepage moving forward.
- The home page is now built with Paragon, allowing it to be easily styled with brand colors / components in both an edX and Open edX context.
- Course sorting / filtering (NEW)
    - An added behavior over the old course dashboard. Clicking the “Refine” button opens options to filter by course status or sort either by most recent enrollment (default) or title.
- Pagination (NEW)
    - All of a user’s courses and entitlements are fetched on page load. To make the page manageable, we paginate that list, showing 25 courses at a time. To view other courses, a user should page through their list of courses using the pagination controls at the bottom of the course list.
- Course Discovery and Recommended Courses are now enabled in a sidebar 
- [See a full list of changes and more details here](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3584589831/2U+New+Learner+Home+Page)

#### What features does this new MFE deprecate?

- The Learner Home project replaces the existing course dashboard (https://courses.edx.org/dashboard) with a new Learner Home page.
 
 ### Community release information

Make sure this MFE follows all [the community requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3561521275/Requirements+for+an+MFE).

- [ ] Is this feature enabled by default? Is it currently enabled?
- [ ] Is this feature internationalized?
- [ ] Is this feature theme-able?
- [ ] What's the production status as of the date of the code cut-off? 

### Code owner 

Primary contact: Vanguards (Arbisoft); 

### Documentation

- [ ] Link to Product blog?
- [ ] Link to "How to enable"
- [ ] Link to any other relevant technical documentation

### Links

* [Related forum thread](https://discuss.openedx.org/t/learners-dashboard-mfe-is-not-ready-for-usage-in-community/10697)

### Tasks

- [x] https://github.com/openedx/frontend-app-learner-dashboard/pull/136
- [x] https://github.com/openedx/public-engineering/issues/194
- [x] https://github.com/openedx/openedx-tutor-plugins/pull/4
- [x] Update frontend-platform to 5.5.1+  (See [#220](https://github.com/openedx/frontend-app-learner-dashboard/pull/220))
- [x] https://github.com/openedx/frontend-app-learner-dashboard/issues/176
- [x] https://github.com/openedx/frontend-app-learner-dashboard/issues/183
- [x] https://github.com/openedx/frontend-app-learner-dashboard/issues/210
- [x] Graduate the plugin to production status (i.e., inclusion in tutor-mfe) by Quince
- [x] https://github.com/openedx/frontend-app-learner-dashboard/issues/235

#### PRs

- [x] https://github.com/openedx/frontend-app-learner-dashboard/pull/205
- [x] https://github.com/openedx/frontend-app-learner-dashboard/pull/220
- [x] https://github.com/openedx/frontend-app-learner-dashboard/pull/209
- [x] https://github.com/openedx/frontend-app-learner-dashboard/pull/219
- [x] https://github.com/openedx/frontend-app-learner-dashboard/pull/238
- [x] https://github.com/openedx/frontend-app-learner-dashboard/pull/232
- [x] https://github.com/openedx/frontend-app-learner-dashboard/pull/230
- [x] https://github.com/openedx/frontend-app-learner-dashboard/pull/237
- [x] https://github.com/openedx/frontend-app-learner-dashboard/pull/243

**Comment by Daniel-hershel** [comment]
### Product scope and features included
What's included?

- The new Learner Home has many of the same features of the old dashboard, with some extended functionality and performance enhancements.
- This release brings the learner home  into our current MFE architecture, and will enable much faster experimentation on the learner homepage moving forward.
- The home page is now built with Paragon, allowing it to be easily styled with brand colors / components in both an edX and Open edX context.
- Course sorting / filtering (NEW)
    - An added behavior over the old course dashboard. Clicking the “Refine” button opens options to filter by course status or sort either by most recent enrollment (default) or title.
- Pagination (NEW)
    - All of a user’s courses and entitlements are fetched on page load. To make the page manageable, we paginate that list, showing 25 courses at a time. To view other courses, a user should page through their list of courses using the pagination controls at the bottom of the course list.
- Course Discovery and Recommended Courses are now enabled in a sidebar 
- [See a full list of changes and more details here](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3584589831/2U+New+Learner+Home+Page)

What features does this new MFE deprecate?

- The Learner Home project replaces the existing course dashboard (https://courses.edx.org/dashboard) with a new Learner Home page.

### Community release information
Product-ready details:
Is this feature enabled by default? Is it currently enabled?
Yes and Yes 
Is this feature internationalized?
Yes
Is this feature theme-able?
Yes
What's the production status as of the date of the code cut-off?
In production on edx.org 
Primary contact: [Daniel Silber-Baker](mailto:dsilber-baker@2u.com) Aurora Team
Documentation details:
Link to Product blog: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3584589831/2U+New+Learner+Home+Page 
Link to "How to enable":
https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3584589831/2U+New+Learner+Home+Page#Developer-FAQ

**Comment by ghassanmas** [comment]
Related PR so it can be included in tutor/open-release frontend-app-learner-dashboard/pull/136

**Comment by michaelwheeler** [comment]
Since this is intended to deprecate the existing course dashboard, what mechanism will be made available to replace the `DashboardRenderStarted` filter (and its related exceptions)?

https://github.com/openedx/openedx-filters/blob/b02caa997e80c82a15bca9df182c480d89b612c8/openedx_filters/learning/filters.py#L425-L495

**Comment by arbrandes** [comment]
@michaelwheeler

> what mechanism will be made available to replace the DashboardRenderStarted filter (and its related exceptions)?

Good question.  As far as I know, there aren't examples of MFEs integrating into the hooks framework.  This might be a good case study for it.  Or, to make things simpler, a study in whatever people use `DashboardRenderStarted` for, and how such mechanisms could be implemented in the Dashboard MFE.  Do you happen to have examples in mind?

**Comment by michaelwheeler** [comment]
At the University of Michigan we are about to deploy an extension that uses `DashboardRenderStarted.RedirectToPage` to redirect users to a custom policy acknowledgment form if they have not yet submitted an acknowledgement.

As for other examples, it looks like the filter was added in https://github.com/openedx/openedx-filters/pull/22. Presumably it was added with some use cases in mind, so perhaps @mariajgrimaldi would have some insight?

**Comment by mariajgrimaldi** [comment]
Hi there folks. 

Filters interacting with the frontend were a temporary solution for frontend extensibility in legacy applications. Now, I believe we should advocate for a replacement in MFEs, although we haven't worked in that direction yet. I hope we can do it soon since much movement lately surrounds MFEs' extensibility.

As for other examples of this kind of filter, we've used similar filters (with `RedirectToPage` exceptions) internally for redirecting to other pages for non-authorized users., eg. [here](https://github.com/eduNEXT/platform-global-teacher-campus/blob/66e4fd7bc7abee4fd62911fbc359686fa8f08c96/platform_global_teacher_campus/filters/pipeline.py#L43-L46) we redirect users from `/maintanance/force_course_publish` to Studio Home to avoid publishing courses from there.

**Comment by NotoriousMKD** [comment]
Will (or could) the issue related to branding include the ability to hide items on the learner dashboard including: Related Programs, Recommendations for You, Upgrade, Grade Required to Pass the Course, and Social Media Buttons?
Ideally, for our on campus use at MIT, we would not show students any of that.

**Comment by arbrandes** [comment]
@NotoriousMKD, most of that will come about via the upcoming pluggability refactor.  We're aiming for Redwood.
