### ISSUE TITLE
xAPI Learning Traces in the Data Lake

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#219]
### Scope and Impact

The high-level goal is to unlock real-time data driven initiatives.

### Child Tasks

- [x] https://github.com/openedx/data-wg/issues/8
- [x] https://github.com/openedx/data-wg/issues/9
- [x] https://github.com/openedx/data-wg/issues/10
- [x] https://github.com/openedx/data-wg/issues/11
- [x] https://github.com/openedx/data-wg/issues/12
- [x] https://github.com/openedx/data-wg/issues/13
