### ISSUE TITLE
Put Initiative Name Here

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#242]
### For Contributing Author:

This is the Primary Product Ticket for the following community contribution: Make course description editable in certificates

### Checklist prior to undergoing Product Review:

The following information is required in order for Product Managers to be able to review your pull request:

- [x] Explanation of the problem being solved
- [x] Description of how users will be impacted, and which users will be impacted
- [x] Screenshots or video showing the functionality or fix, before and after
- [x] Reproduction steps and/or testing steps

Only if necessary:

- [ ] If necessary, links to corresponding configuration changes
- [ ] If necessary, links to corresponding enablement changes, particularly waffle/toggle status details

### Related PRs

- [ ] https://github.com/openedx/edx-platform/pull/29850

### For Product Manager doing the review:

What criteria should be analyzed from Product to approve a PR?

- The problem being solved by the feature or fix is clear.
- There is clarity on how the change or fix will impact the end user.
- It is clear that the change will not negatively impact users or other areas of the platform.
- The change is implemented comprehensively.
- Any changes to UI use the current, standard Paragon Design System: https://paragon-openedx.netlify.app/

### Context & Background

v

### Scope & Approach

v

### Value & Impact

v

### Milestones and/or Epics

v

### Named Release

v

### Timeline

v

### Proposed By

v

### Additional Info

v

**Comment by jmakowski1123** [comment]
Info from PR:

## Description

This change adds a new waffle switch to redirect a student to courseware after enrolment instead of the dashboard.

## Supporting information

NA

## Testing instructions

- With a new toggle disabled, enrol a student into a course. They will be redirected to the dashboard after enrolment. 
- With a new toggle enabled, enrol a student into a course. They will be redirected to the course after enrolment. 

## Deadline

"None"

## Other information

Private-ref: [BB-7071](https://tasks.opencraft.com/browse/BB-7051)

**Comment by ProductRyan** [comment]
@xitij2000 I am curious what the goal of this work is... what is the use case and how does bypassing the dashboard create value for you?

**Comment by xitij2000** [comment]
This is a customisation that we are carrying for a client due to their requirements. We generally prefer to ensure that any customisations are upstreamed and available to the wider community. 

In this case creating a hook/filter based system for this seemed like an overkill, so we went for a simpler config based approach, but are open to different approaches that maintain our clients preferred experience.

**Comment by ProductRyan** [comment]
@xitij2000 can you illuminate your client's use case? what's the reason that they want to bypass the dashboard? do their learners only ever access a single course?

The reason that I ask is that most navigation paths begin with the dashboard and the ramifications for skipping that page in the user's journey may have unintended consequences - I want to make sure we don't add complexity that could get a learner lost.

**Comment by xitij2000** [comment]
> @xitij2000 can you illuminate your client's use case? what's the reason that they want to bypass the dashboard? do their learners only ever access a single course?
> 
> The reason that I ask is that most navigation paths begin with the dashboard and the ramifications for skipping that page in the user's journey may have unintended consequences - I want to make sure we don't add complexity that could get a learner lost.

I think with this change the dashboard is still available and as prominent, it is only skipped in one situation, which is when a user enrols in a course, they are taken to that course immediately instead of to the dashboard first. 

On login from the home page, users will still see their dashboard first, so other courses will still be as accessible as before.

**Comment by mphilbrick211** [comment]
> Hi @ProductRyan! Just checking to see if there's any updates here?

@ProductRyan Hi Ryan, any updates on status?

**Comment by mphilbrick211** [comment]
Hi @ProductRyan - just checking to see if there's an update here?

**Comment by mphilbrick211** [comment]
> @mphilbrick211 Just checking in here to see if I can do anything to help move this along.

Hi @xitij2000! I believe @jmakowski1123 recently escalated this to @ProductRyan, so I think there should be an update soon!

**Comment by mphilbrick211** [comment]
HI @ProductRyan - just checking in on this!

**Comment by mphilbrick211** [comment]
Hi @ProductRyan - friendly ping on this

**Comment by ProductRyan** [comment]
Sorry for the delay. I think this is a good addition as long as it's toggle-able. Thanks for this!

**Comment by itsjeyd** [comment]
@jmakowski1123 @mphilbrick211 It looks like this is done; the PR for it (https://github.com/openedx/edx-platform/pull/31715) has been merged. Can we close this ticket and move it to Shipped on the [roadmap](https://github.com/orgs/openedx/projects/4/views/20)?
