### ISSUE TITLE
Upgrade Node JS from 16 to 18

### ISSUE THREAD

**Issue by abdullahwaheed** [openedx/platform-roadmap#243]
### Abstract

edX MFEs are currently using Node JS 16 across the board. We have to upgrade each MFE to use Node JS 18.

### Context & Background

Node 16's support will end on [September 11, 2023](https://nodejs.org/en/blog/announcements/nodejs16-eol/). So we have to upgrade node before that. We are planning to add it in Palm release

### Scope & Approach

We have tested some MFEs with node 18 upgrade and there were minimal or no changes. So we are confident that we can upgrade it without much changes and on time

### Value & Impact

If we skip this upgrade, we won't get security upgrades in Node after this September.

### Milestones and/or Epics

https://github.com/edx/upgrades/issues/108

### Named Release

Palm

### Timeline

**Start Date**: March 7th, 2023
**End Date**:  May 19th, 2023

### Proposed By

2u

```[tasklist]
### Tasks
- [ ] https://github.com/edx/frontend-component-footer-edx/issues/259
- [ ] https://github.com/edx/frontend-component-header-edx/issues/356
- [ ] https://github.com/edx/gatsby-source-portal-designer/issues/47
- [ ] https://github.com/openedx/browserslist-config/issues/11
- [ ] https://github.com/openedx/credentials/issues/1969
- [ ] https://github.com/openedx/edx-analytics-dashboard/issues/1429
- [ ] https://github.com/openedx/edx-bootstrap/issues/217
- [ ] https://github.com/openedx/edx-enterprise/issues/1730
- [ ] https://github.com/openedx/edx-ui-toolkit/issues/310
- [ ] https://github.com/openedx/eslint-config/issues/121
- [ ] https://github.com/openedx/frontend-app-account/issues/760
- [ ] https://github.com/openedx/frontend-app-admin-portal/issues/978
- [ ] https://github.com/openedx/frontend-app-authn/issues/780
- [ ] https://github.com/openedx/frontend-app-communications/issues/121
- [ ] https://github.com/openedx/frontend-app-course-authoring/issues/462
- [ ] https://github.com/openedx/frontend-app-discussions/issues/473
- [ ] https://github.com/openedx/frontend-app-ecommerce/issues/269
- [ ] https://github.com/openedx/frontend-app-enterprise-public-catalog/issues/300
- [ ] https://github.com/openedx/frontend-app-gradebook/issues/318
- [ ] https://github.com/openedx/frontend-app-learner-portal-enterprise/issues/691
- [ ] https://github.com/openedx/frontend-app-learner-portal-programs/issues/271
- [ ] https://github.com/openedx/frontend-app-learner-record/issues/148
- [ ] https://github.com/openedx/frontend-app-learning/issues/1085
- [ ] https://github.com/openedx/frontend-app-library-authoring/issues/122
- [ ] https://github.com/openedx/frontend-app-ora-grading/issues/173
- [ ] https://github.com/openedx/frontend-app-payment/issues/720
- [ ] https://github.com/openedx/frontend-app-profile/issues/714
- [ ] https://github.com/openedx/frontend-app-program-console/issues/105
- [ ] https://github.com/openedx/frontend-app-publisher/issues/827
- [ ] https://github.com/openedx/frontend-build/issues/318
- [ ] https://github.com/openedx/frontend-component-footer/issues/276
- [ ] https://github.com/openedx/frontend-component-header/issues/315
- [ ] https://github.com/openedx/frontend-enterprise/issues/307
- [ ] https://github.com/openedx/frontend-lib-content-components/issues/279
- [ ] https://github.com/openedx/frontend-lib-special-exams/issues/91
- [ ] https://github.com/openedx/frontend-platform/issues/455
- [ ] https://github.com/openedx/frontend-template-application/issues/557
- [ ] https://github.com/openedx/paragon/issues/2143
- [ ] https://github.com/openedx/studio-frontend/issues/375
- [ ] https://github.com/openedx/stylelint-config-edx/issues/27
```

**Comment by feanil** [comment]
`analytics-dashboard` and `studio-frontend` are both deprecated so we won't prioritize those upgrades.  `edx-platform` is still needed but we're about to kick-off the upgarde to Node 20, so we will collect edx-platform as a part of that upgrade procedure.  Everything else has been closed.  As of now, I'm considering this work completed.  Work to unblock the edx-platform upgrade should continue but we don't need this top-level epic to track it anymore.
