### ISSUE TITLE
Tutor Adoption

### ISSUE THREAD

**Issue by kdmccormick** [openedx/platform-roadmap#244]
### Abstract
 
Drive adoption of Tutor as the unified, extensible, easy-to-use development environment for Open edX.

### Context & Background

...

### Scope & Approach

...

### Value & Impact

...

### Milestones and/or Epics

```[tasklist]
### Epics
- [ ] https://github.com/openedx/platform-roadmap/issues/114
- [ ] https://github.com/openedx/platform-roadmap/issues/122
- [ ] https://github.com/openedx/platform-roadmap/issues/116
- [ ] https://github.com/openedx/platform-roadmap/issues/202
- [ ] https://github.com/openedx/platform-roadmap/issues/123
- [ ] https://github.com/openedx/platform-roadmap/issues/152
- [ ] https://github.com/openedx/public-engineering/issues/247
- [ ] https://github.com/openedx/platform-roadmap/issues/117
```

### Named Release

Possible timeline:

**Nutmeg**: initial Tutor improvements
**Olive**: more improvements
**Palm**: more improvements, begin transition from Devstack to Tutor
**Quince**: finish transition to Tutor
**R**: removal of Devstack

Iterative over Nutmeg, Olive, Palm, Quince

### Timeline

Early 2022 to late 2023 (estimate)

### Proposed By

tCRIL

**Comment by kdmccormick** [comment]
We have made a lot of progress on improving Tutor as a development environment. Tutor isn't perfect, but Devstack has officially been deprecated, which will be a sort of forcing function towards continuous improvement for Tutor.

I'm closing this, as there is no longer a specific effort to work on the remaining items, but we have a newly-organized [Tutor Maintainers team](https://discuss.openedx.org/t/tutor-maintainers/7287) which will continue to chip away at Tutor improvements as needed. I've moved all remaining issues to the [DevOps WG repo](https://github.com/openedx/wg-devops/issues).
