### ISSUE TITLE
React Router Upgrade to v6

### ISSUE THREAD

**Issue by abdullahwaheed** [openedx/platform-roadmap#276]
### Abstract

[React Router](https://reactrouter.com/en/main) has upgraded react router to v6 with some exciting changes and major breaking changes.

### Context & Background

Most of the edx MFEs uses react router 5, primarily from frontend-platform. So, to use react router to v6, we have to upgrade it in all the consumer MFEs of frontend platform, which requires a lot of code changes.

### Scope & Approach

FED-BOM will update frontend-platform and its consumer MFEs and will ask the owning teams to review and test the functionality and then deploy

### Value & Impact

After this upgrade, all the MFEs of would use latest react router and can benefit from the features provided in the latest version

### Milestones and/or Epics

[Update frontend-platform's react-router version](https://github.com/openedx/wg-frontend/issues/153)
[React Router v6 upgrade](https://openedx.atlassian.net/wiki/spaces/AC/pages/3792306208/React+Router+v6+upgrade)

### Named Release

Q

### Timeline

End Date: 15th July 2023

### Proposed By

2u

### Tasks
- [x] [Create a roadmap issue](https://github.com/openedx/platform-roadmap/issues/new/choose) in the platform-roadmap repository
- [x] Add this checklist to the roadmap issue's description
- [x] Add the "maintenance" label to the roadmap issue
- [x] Add the roadmap issue to the Backlog column of the [Open edX Roadmap](https://github.com/orgs/openedx/projects/4/views/1) project
- [x] Set appropriate values for the roadmap project's custom fields for the issue (especially "Proposed by", "Platform map - Super Level", "Strategy", and "Type")
- [x] Set an appropriate release milestone for the roadmap issue
- [x] Add an explicit target completion date to the roadmap issue description, and explain there why it was chosen
- [ ] Select an orchestration team
- [ ] Name the orchestration team in the roadmap issue description
- [ ] Create a repo health check to identify most/all of the repositories impacted by the upgrade (and ideally, whether or not the upgrade is believed to be complete)
- [x] Create a new value for the "Project" field in the [Maintenance](https://github.com/orgs/edx/projects/17/views/1) project board for this upgrade project
- [ ] Create a new view in the Maintenance project board that filters down to only the issues in this upgrade project
- [ ] Create an issue in each impacted repository for the upgrade, and add it to the Todo column of the [Maintenance](https://github.com/orgs/edx/projects/17/views/1) project board; specify at least the "Project" and "Source" field for each issue (and "Owner" also if you're a 2U or Arbisoft employee)
- [x] Create a [task list](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-tasklists) in the roadmap issue listing all of the impacted repository issues
- [x] Create a page under [Upgrades](https://openedx.atlassian.net/wiki/spaces/AC/pages/1165395730) in Confluence for documentation related to the upgrade
- [x] Add a link to the Confluence page from the roadmap issue
- [x] Add a link to the roadmap issue from the Confluence page
- [ ] Document in a Confluence child page the changes believed to be most problematic and/or interesting about the upgrade
- [ ] Create a ticket to determine the appropriate amount of automation (codemods, repo health checks, etc.) to create for the upgrade
- [ ] Perform the automation discovery work and write upgrade instructions for all project participants in a Confluence child page
- [x] Link to the upgrade instructions from the roadmap issue
- [ ] Send an [announcement](https://openedx.atlassian.net/wiki/spaces/AC/pages/3702325257/Upgrade-Related+Announcements) of the upgrade, asking code maintainers to read the upgrade instructions and select an upgrade service level for each impacted repository in its corresponding issue
- [ ] Create issues in [public-engineering](https://github.com/openedx/public-engineering) for each external dependency which still needs code changes and/or a release to support the upgrade
- [ ] Add the "help wanted" and "maintenance" labels to each public-engineering issue created above
- [ ] Add each public-engineering issue created above to the Maintenance project board
- [ ] Set appropriate values for the Maintenance project board custom fields for each added public-engineering issue
- [ ] Ask the Open edX developer community (especially Core Committers) for assistance with the added public-engineering issues
- [ ] Create [Build-Test-Release Working Group](https://github.com/orgs/openedx/projects/28) and/or 2U SRE tickets if they will need to do work for the upgrade
- [ ] Complete and update all of the created implementation tickets
- [ ] Deploy all of the updated services
- [ ] Update the [support windows spreadsheet](https://docs.google.com/spreadsheets/d/11DheEtMDGrbA9hsUvZ2SEd4Cc8CaC4mAfoV8SVaLBGI/edit#gid=195838733) to correctly indicate the version now used
- [ ] [Announce](https://openedx.atlassian.net/wiki/spaces/AC/pages/3702325257) the successful completion of the upgrade
- [ ] Make sure any deployment instructions make it into the release notes of the next Open edX named release (collaborate with the BTR WG)
- [ ] Remove any CI matrix entries for no-longer-supported versions of the dependency
- [ ] Remove the Maintenance project board view/tab created for the upgrade
- [ ] Stop running repo health checks related to the upgrade which are no longer relevant
- [ ] Schedule and run a retrospective meeting about the upgrade
- [x] Update the [Upgrade Project Runbook](https://openedx.atlassian.net/wiki/spaces/AC/pages/3660316693/Upgrade+Project+Runbook) based on retrospective findings, if appropriate
- [ ] Mark the roadmap issue for the upgrade as complete
- [ ] Move the root Confluence page for this upgrade’s docs under [Past Upgrades](https://openedx.atlassian.net/wiki/spaces/AC/pages/1883865104)
- [ ] Ticket work to replace or take over dependencies which were found during the upgrade to be inadequately maintained

**Comment by abdullahwaheed** [comment]
label: maintenance
