### ISSUE TITLE
Redis 7.2 Upgrade

### ISSUE THREAD

**Issue by mumarkhan999** [openedx/platform-roadmap#283]
### Abstract

Redis 7.2 is available for the community. To keep our tech-stack updated, we need to upgrade Redis to the latest version.

### Context & Background

According to our [Support Windows Spreadsheet,](https://docs.google.com/spreadsheets/d/11DheEtMDGrbA9hsUvZ2SEd4Cc8CaC4mAfoV8SVaLBGI/edit#gid=195838733) we should upgrade Redis to latest LTS release before the mid of 2024.

### Scope & Approach

The initial approach for this issue is as following (It'll be updated later on):

- @openedx/arbi-bom team will be the one responsible for managing this upgrade among all services and provide any help to the teams if needed or requested by the other teams.
- All the private and public repos (containing the usage of redis python client) under edx and openedx organisations will be updated.
- All the owning teams will be approached to have their preferred method to upgrade the repositories under their ownership and collaborate to complete the task before the supposed deadline.

### Value & Impact

Updating the Redis version to the latest LTS version Redis 7.2 will provide long-term security upgrade assurance.

### Milestones and/or Epics

```[tasklist]
### Tasks
- [ ] [Create a roadmap issue](https://github.com/openedx/platform-roadmap/issues/new/choose) in the platform-roadmap repository
- [ ] Add this checklist to the roadmap issue's description
- [ ] Add the "maintenance" label to the roadmap issue
- [ ] Add the roadmap issue to the Backlog column of the [Open edX Roadmap](https://github.com/orgs/openedx/projects/4/views/1) project
- [ ] Set appropriate values for the roadmap project's custom fields for the issue (especially "Proposed by", "Platform map - Super Level", "Strategy", and "Type")
- [ ] Set an appropriate release milestone for the roadmap issue
- [ ] Add an explicit target completion date to the roadmap issue description, and explain there why it was chosen
- [ ] Select an orchestration team
- [ ] Name the orchestration team in the roadmap issue description
- [ ] Create a repo health check to identify most/all of the repositories impacted by the upgrade (and ideally, whether or not the upgrade is believed to be complete)
- [ ] Create a new value for the "Project" field in the [Maintenance](https://github.com/orgs/openedx/projects/51/views/1) project board for this upgrade project
- [ ] Create a new view in the Maintenance project board that filters down to only the issues in this upgrade project
- [ ] Create an issue in each impacted repository for the upgrade, and add it to the Todo column of the [Maintenance](https://github.com/orgs/openedx/projects/51/views/1) project board; specify at least the "Project" and "Source" field for each issue (and "Owner" also if you're a 2U or Arbisoft employee)
- [ ] Create a [task list](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-tasklists) in the roadmap issue listing all of the impacted repository issues
- [ ] Create a page under [Upgrades](https://openedx.atlassian.net/wiki/spaces/AC/pages/1165395730) in Confluence for documentation related to the upgrade
- [ ] Add a link to the Confluence page from the roadmap issue
- [ ] Add a link to the roadmap issue from the Confluence page
- [ ] Document in a Confluence child page the changes believed to be most problematic and/or interesting about the upgrade
- [ ] Create a ticket to determine the appropriate amount of automation (codemods, repo health checks, etc.) to create for the upgrade
- [ ] Perform the automation discovery work and write upgrade instructions for all project participants in a Confluence child page
- [ ] Link to the upgrade instructions from the roadmap issue
- [ ] Send an [announcement](https://openedx.atlassian.net/wiki/spaces/AC/pages/3702325257/Upgrade-Related+Announcements) of the upgrade, asking code maintainers to read the upgrade instructions and select an upgrade service level for each impacted repository in its corresponding issue
- [ ] Create issues in [public-engineering](https://github.com/openedx/public-engineering) for each external dependency which still needs code changes and/or a release to support the upgrade
- [ ] Add the "help wanted" and "maintenance" labels to each public-engineering issue created above
- [ ] Add each public-engineering issue created above to the Maintenance project board
- [ ] Set appropriate values for the Maintenance project board custom fields for each added public-engineering issue
- [ ] Ask the Open edX developer community (especially Core Committers) for assistance with the added public-engineering issues
- [ ] Create [Build-Test-Release Working Group](https://github.com/orgs/openedx/projects/28) and/or 2U SRE tickets if they will need to do work for the upgrade
- [ ] Complete and update all of the created implementation tickets
- [ ] Deploy all of the updated services
- [ ] Update the [support windows spreadsheet](https://docs.google.com/spreadsheets/d/11DheEtMDGrbA9hsUvZ2SEd4Cc8CaC4mAfoV8SVaLBGI/edit#gid=195838733) to correctly indicate the version now used
- [ ] [Announce](https://openedx.atlassian.net/wiki/spaces/AC/pages/3702325257) the successful completion of the upgrade
- [ ] Make sure any deployment instructions make it into the release notes of the next Open edX named release (collaborate with the BTR WG)
- [ ] Remove any CI matrix entries for no-longer-supported versions of the dependency
- [ ] Remove the Maintenance project board view/tab created for the upgrade
- [ ] Stop running repo health checks related to the upgrade which are no longer relevant
- [ ] Schedule and run a retrospective meeting about the upgrade
- [ ] Update the [Upgrade Project Runbook](https://openedx.atlassian.net/wiki/spaces/AC/pages/3660316693/Upgrade+Project+Runbook) based on retrospective findings, if appropriate
- [ ] Mark the roadmap issue for the upgrade as complete
- [ ] Move the root Confluence page for this upgrade’s docs under [Past Upgrades](https://openedx.atlassian.net/wiki/spaces/AC/pages/1883865104)
- [ ] Ticket work to replace or take over dependencies which were found during the upgrade to be inadequately maintained
```

### Named Release

Quince

### Timeline

Due Date: Sep 30th, 2023 - The due date is before the deadline to cut branches for the next target release.

### Proposed By

2U

**Comment by jmakowski1123** [comment]
@feanil Flagging this request that come in. Are there any current efforts underway around this upgrade, or do you see a path to prioritizing? If not, we can track it in the product roadmap backlog.

**Comment by feanil** [comment]
@jmakowski1123 [tutor already runs with Redis 7.2](https://github.com/overhangio/tutor/blob/master/tutor/templates/config/defaults.yml#L25) so I think the issue is probably specific to edx.org and not relevant to the community given the other tickets this was referenced in.  So from the community perspective this work is done and I don't really expect any major issues running with redis 7.2.x
