### ISSUE TITLE
Initiative: Studio MFE Conversion

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#322]
This is an umbrella, initiative-level ticket to track all of the child tickets associated with the Studio MFE Conversion. These tickets are all slated for Redwood.

```[tasklist]
- [ ] https://github.com/openedx/platform-roadmap/issues/316
- [ ] https://github.com/openedx/platform-roadmap/issues/321
- [ ] https://github.com/openedx/platform-roadmap/issues/320
- [ ] https://github.com/openedx/platform-roadmap/issues/319
- [ ] https://github.com/openedx/platform-roadmap/issues/318
- [ ] https://github.com/openedx/platform-roadmap/issues/317
```

Related FC ticket: https://github.com/aximcollaborative/funded-contributions/issues/61

**Comment by kdmccormick** [comment]
A big chunk of this was shipped in Redwood, but there is more to finish before Sumac.
