### ISSUE TITLE
Reintroduce left-sidebar navigation

### ISSUE THREAD

**Issue by crathbun428** [openedx/platform-roadmap#329]
**At-A-Glance**
The goal of this release is to restore the left-sidebar navigation as the default user experience for learners on the in-course experience pages of the LMS. The left-sidebar navigation must allow the user to view the course structure and content, their own completion statuses of the course section, subsection and units, and easily navigate to course sections, subsections, and units. 

The existing horizontal unit-level navigation allowing users to navigate from component to component will remain for the sake of this initial Phase 1 release with the idea that user testing will be conducted in the future to better understand the best user experience for viewing and navigating between course components. 

The UI for this initial release will take into account the right-sidebar on these in-course experience pages as well. The right-sidebar displays in-context discussion activity.

[Product requirements](https://openedx.atlassian.net/l/cp/HLwZzUba)

**More information**
[Design files](https://www.figma.com/file/RCy53uUGxCyFG9wV7BfpXj/Open_edX_side_nav?type=design&node-id=594%3A3510&mode=design&t=QQAQxh7WkDO7N5Qn-1)
[Phased release plan](https://docs.google.com/document/d/1s2CYEFB5OkwlIeTCzt2RANRM0wlaCcB2fpMy7qjVtYE/edit?usp=sharing)

**Key Stakeholders**
Axim Collaborative
WGU
Pearson
2U

**Community release milestones**
Redwood: Phase 1
Sumac: Phase 2

## Associated PRs:

Phase1:

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/edx-platform/pull/34457
- [ ] https://github.com/openedx/edx-platform/pull/34747
- [ ] https://github.com/openedx/edx-platform/pull/34650
- [ ] https://github.com/openedx/frontend-app-learning/pull/1375
```

Phase2:

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/edx-platform/pull/34816
- [ ] https://github.com/openedx/edx-platform/pull/34856
- [ ] https://github.com/openedx/frontend-app-learning/pull/1386
- [ ] https://github.com/openedx/frontend-app-learning/pull/1398
```

Sidebar as a Plugin:

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/frontend-app-learning/pull/1349
```

**Comment by jmakowski1123** [comment]
Original proposal for product review approval tracking purposes: https://github.com/openedx/platform-roadmap/issues/309
