### ISSUE TITLE
Upgrade Node JS to 20

### ISSUE THREAD

**Issue by feanil** [openedx/platform-roadmap#363]
### Description

Node 18 is already in maintenance status, and support will end on 2025-04-30.  Node 20 is the current LTS release, with a corresponding End-of-life of 2026-04-30.  We should migrate to the latter before support runs out on 18.

Taking how long the Node 16 upgrade took, there is some urgency in starting this.  A full year sounds like a lot, but it might not be.
 
```[tasklist]
### Tasks
- [ ] openedx/public-engineering#230
- [ ] openedx/public-engineering#267
- [ ] openedx/public-engineering#232
- [ ] https://github.com/overhangio/tutor-mfe/issues/198
- [ ] https://github.com/openedx/edx-platform/pull/34311
```
