### ISSUE TITLE
Ubuntu Upgrade

### ISSUE THREAD

**Issue by feanil** [openedx/platform-roadmap#377]
Ubuntu 20.04 which we use as the base for all of our backend services is going to be losing security Support in February 2025.  This means we need to move to ubuntu 22.04 or 24.04 before the Sumac release to not be on an unsupported version of Ubuntu for Teak.

**Unless there is a specific issue that requires testing on specific ubuntu versions, we should move all workflows to use the `ubuntu-latest` GitHub Actions worker.**

```[tasklist]
### Prioritized Released Services
- [ ] https://github.com/openedx/credentials/issues/2545
- [ ] https://github.com/openedx/edx-platform/issues/35314
- [ ] https://github.com/openedx/course-discovery/issues/4410
- [ ] https://github.com/openedx/codejail/issues/186
- [ ] https://github.com/openedx/edx-notes-api/issues/424
- [ ] https://github.com/openedx/xqueue/issues/945
- [ ] https://github.com/openedx/xqueue-watcher/issues/114
```

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/.github/issues/149
- [ ] https://github.com/openedx/mockprock/issues/50
- [ ] https://github.com/openedx/cc2olx/issues/211
- [ ] https://github.com/openedx/ecommerce/issues/4180
- [ ] https://github.com/openedx/completion/issues/312
- [ ] https://github.com/openedx/registrar/issues/639
- [ ] https://github.com/openedx/XBlock/issues/780
- [ ] https://github.com/openedx/web-fragments/issues/218
- [ ] https://github.com/openedx/django-pyfs/issues/217
- [ ] https://github.com/openedx/DoneXBlock/issues/247
- [ ] https://github.com/openedx/crowdsourcehinter/issues/170
- [ ] https://github.com/openedx/AudioXBlock/issues/158
- [ ] https://github.com/openedx/FeedbackXBlock/issues/113
- [ ] https://github.com/openedx/RecommenderXBlock/issues/94
- [ ] https://github.com/openedx/opaque-keys/issues/332
- [ ] https://github.com/openedx/event-tracking/issues/314
- [ ] https://github.com/openedx/edx-bootstrap/issues/294
- [ ] https://github.com/openedx/edx-ace/issues/298
- [ ] https://github.com/openedx/openedx-ledger/issues/108
- [ ] https://github.com/openedx/openedx-learning/issues/210
- [ ] https://github.com/openedx/openedx-calc/issues/106
- [ ] https://github.com/openedx/help-tokens/issues/221
- [ ] https://github.com/openedx/edx-val/issues/519
- [ ] https://github.com/openedx/auth-backends/issues/330
- [ ] https://github.com/openedx/enterprise-subsidy/issues/287
- [ ] https://github.com/openedx/enterprise-catalog/issues/910
- [ ] https://github.com/openedx/brand-openedx/issues/24
- [ ] https://github.com/openedx/openedx-filters/issues/206
- [ ] https://github.com/openedx/enterprise-access/issues/539
- [ ] https://github.com/openedx/taxonomy-connector/issues/200
- [ ] https://github.com/openedx/super-csv/issues/191
- [ ] https://github.com/openedx/i18n-tools/issues/153
- [ ] https://github.com/openedx/edx-milestones/issues/87
- [ ] https://github.com/openedx/xblock-skill-tagging/issues/40
- [ ] https://github.com/openedx/xblock-google-drive/issues/118
- [ ] https://github.com/openedx/edx-celeryutils/issues/301
- [ ] https://github.com/openedx/xss-utils/issues/247
- [ ] https://github.com/openedx/openedx-events/issues/383
- [ ] https://github.com/openedx/edx-ora2/issues/2223
- [ ] https://github.com/openedx/license-manager/issues/695
- [ ] https://github.com/openedx/edx-rbac/issues/315
- [ ] https://github.com/openedx/acid-block/issues/177
- [ ] https://github.com/openedx/xblock-sdk/issues/393
- [ ] https://github.com/openedx/openedx-webhooks/issues/297
- [ ] https://github.com/openedx/edx-submissions/issues/259
- [ ] https://github.com/openedx/edx-organizations/issues/405
- [ ] https://github.com/openedx/repo-tools/issues/551
- [ ] https://github.com/openedx/openedx-chem/issues/91
- [ ] https://github.com/openedx/edx-toggles/issues/375
- [ ] https://github.com/openedx/edx-when/issues/266
- [ ] https://github.com/openedx/code-annotations/issues/113
- [ ] https://github.com/openedx/user-util/issues/28
- [ ] https://github.com/openedx/edx-enterprise/issues/2204
- [ ] https://github.com/openedx/edx-cookiecutters/issues/478
- [ ] https://github.com/openedx/edx-lint/issues/443
- [ ] https://github.com/openedx/studio-frontend/issues/393
- [ ] https://github.com/openedx/openedx-atlas/issues/56
- [ ] https://github.com/openedx/edx-search/issues/154
- [ ] https://github.com/openedx/edx-proctoring/issues/1224
- [ ] https://github.com/openedx/ecommerce-worker/issues/281
- [ ] https://github.com/openedx/ecommerce-scripts/issues/207
- [ ] https://github.com/openedx/codejail-includes/issues/15
- [ ] https://github.com/openedx/platform-plugin-aspects/issues/77
- [ ] https://github.com/openedx/frontend-app-authn/issues/1299
- [ ] https://github.com/openedx/edx-enterprise-data/issues/479
- [ ] https://github.com/openedx/edx-django-release-util/issues/73
- [ ] https://github.com/openedx/frontend-app-payment/issues/876
- [ ] https://github.com/openedx/event-routing-backends/issues/445
- [ ] https://github.com/openedx/event-bus-redis/issues/117
- [ ] https://github.com/openedx/edx-django-utils/issues/437
- [ ] https://github.com/openedx/react-unit-test-utils/issues/32
- [ ] https://github.com/openedx/tutor-contrib-coursegraph/issues/41
- [ ] https://github.com/openedx/tinymce-language-selector/issues/21
- [ ] https://github.com/openedx/cs_comments_service/issues/434
- [ ] https://github.com/openedx/xapi-db-load/issues/121
- [ ] https://github.com/openedx/frontend-app-gradebook/issues/401
- [ ] https://github.com/openedx/edx-drf-extensions/issues/471
- [ ] https://github.com/openedx/edx-repo-health/issues/513
- [ ] https://github.com/openedx/api-doc-tools/issues/291
- [ ] https://github.com/openedx/stylelint-config-edx/issues/41
- [ ] https://github.com/openedx/frontend-slot-footer/issues/27
- [ ] https://github.com/openedx/event-bus-kafka/issues/264
- [ ] https://github.com/openedx/edx-ui-toolkit/issues/433
- [ ] https://github.com/openedx/xblock-lti-consumer/issues/496
- [ ] https://github.com/openedx/staff_graded-xblock/issues/260
- [ ] https://github.com/openedx/pytest-repo-health/issues/298
- [ ] https://github.com/openedx/frontend-app-publisher/issues/975
- [ ] https://github.com/openedx/open-edx-proposals/issues/623
- [ ] https://github.com/openedx/django-config-models/issues/374
- [ ] https://github.com/openedx/xblock-image-explorer/issues/147
- [ ] https://github.com/openedx/frontend-app-ecommerce/issues/392
- [ ] https://github.com/openedx/edx-bulk-grades/issues/165
- [ ] https://github.com/openedx/django-user-tasks/issues/369
- [ ] https://github.com/openedx/xblock-in-video-quiz/issues/205
- [ ] https://github.com/openedx/frontend-app-learner-dashboard/issues/420
- [ ] https://github.com/openedx/edx-rest-api-client/issues/358
- [ ] https://github.com/openedx/edx-django-sites-extensions/issues/61
- [ ] https://github.com/openedx/frontend-app-ora-grading/issues/345
- [ ] https://github.com/openedx/django-lang-pref-middleware/issues/257
- [ ] https://github.com/openedx/edx-enterprise-subsidy-client/issues/104
- [ ] https://github.com/openedx/frontend-app-learner-portal-programs/issues/320
- [ ] https://github.com/openedx/xblock-drag-and-drop-v2/issues/423
- [ ] https://github.com/openedx/frontend-component-cookie-policy-banner/issues/441
```

**Comment by kdmccormick** [comment]
@feanil I thought we were going to ubuntu-latest. @pomegranited has [already opened 24.04 PRs](https://github.com/openedx/edx-submissions/issues/259). Should we update all these issues and those PRs to say ubuntu-latest?

**Comment by pomegranited** [comment]
@kdmccormick Oh, those issues do say:

> opt to set it to `ubuntu-latest` instead if it doesn't matter what version it's running on

I can't imagine it'll matter for my repos, and it'd be good to have advance notice of issues. I'll fix those PRs up now.

**Comment by feanil** [comment]
Hello, yes please go to ubuntu-latest as much as possible.  I had planned on writing this up but did not get enough time before I went on PTO.  I think the codejail repo is probably the only one that needs to be testing with specific versions of Ubuntu and everything else should just use `ubunt-latest` unless there is a good reason not to.

**Comment by feanil** [comment]
Due to issues with codejail and 24.04 that we weren't able to resolve, we'll only be able to add 22.04 support for edx-platform.  All other services should support 24.04 but edx-platform will only support 22.04

**Comment by feanil** [comment]
All repos support at least Ubuntu 22.04 and since most repos are agnostic of the underlying OS, they are now simply testing with the latest version of ubuntu and should work with any OS where the correct version of python and node are supplied.

For all top-level Django services, they support running with Ubuntu 24.04 except for edx-platform that supports running on Ubuntu 22.04 as of the closing of this issue.
