### ISSUE TITLE
Update `frontend-app-ora` to use Design Tokens

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/platform-roadmap#401]
```[tasklist]
### Tasks
- [ ] Create draft PR updating MFE to use Design tokens
- [ ] Ensure draft PR is using released versions of `paragon`/`frontend-build`/`frontend-platform` from `npm`
- [ ] Set up sandbox to test draft PR
- [ ] Get draft PR approved
- [ ] Create new `master-design-tokens` branch off of latest `master`
- [ ] Update PR to point to `master-design-tokens`, move out of draft
- [ ] Merge PR
```
